version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: url-shrtnr-postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - url-shrtnr-network

  # NestJS API
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: url-shrtnr-api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/url_shortener
      JWT_ACCESS_TOKEN_SECRET: your-access-token-secret
      JWT_REFRESH_TOKEN_SECRET: your-refresh-token-secret
      JWT_TOKEN_ISSUER: url-shrtnr
      GOOGLE_CLIENT_ID: your-google-client-id
      GOOGLE_CLIENT_SECRET: your-google-client-secret
      DOMAIN_NAME: localhost
      APP_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - url-shrtnr-network
    restart: unless-stopped

  # Next.js Web App
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: url-shrtnr-web
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3000
    ports:
      - "4321:4321"
    depends_on:
      - api
    networks:
      - url-shrtnr-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  url-shrtnr-network:
    driver: bridge
